### ISSUE TITLE
[Feature Request] Restart All Timers

### ISSUE THREAD

**Issue by buitim** [URK96/ResinTimer#10]
Hi! Thanks for this great app! I was just curious if it would be possible to add a function to restart all of the timers on a view with one button? So instead of having to tap each one then restarting it, we could click one button to restart them all. This functionality would be nice on pages like the picture attached. ![image](https://user-images.githubusercontent.com/29244321/119446377-2e944880-bce3-11eb-9a0d-23815b7450f4.png)

This would be nice if there were people like me who collect all expedition rewards at once. 

Keep up the awesome work!

**Comment by URK96** [comment]
Thanks to suggest new feature. I will add all reset feature to update list    x~x

**Comment by buitim** [comment]
Thanks for adding this in the latest update! I'll go ahead and close this issue.
