### ISSUE TITLE
[Suggestion] Similar App but for Honkai Impact

### ISSUE THREAD

**Issue by JustAKat** [URK96/ResinTimer#12]
Hi, been using your Resin Timer for Genshin app for a while now, been quite useful.

Was wondering, if you might be open to making a similar app for Honkai Stamina Notification? No such app exists yet, and it would be helpful for people to get notified when they get x Stamina.

1 Stamina recharges per 6 minutes.
Max Stamina varies based on Captain Level, but maybe you could let people input max Stamina themselves, starts from like 90 for new players.

Typical stamina usage can vary, but common ones seems to be 10, 20, 30, but also has ones like 8, 16, 17, 18, etc, for stories and other side stuff.

**Comment by URK96** [comment]
Thanks to suggest your opinion

I will consider to make Honkai Impact stamina timer app :)
