### ISSUE TITLE
Not wotk on win11

### ISSUE THREAD

**Issue by MenBS** [URK96/ResinTimer#15]
Hi.
App dont work on win11.

-  when trying to set a value (e.g. resin counter), the application exits unexpectedly

-  a number of menu items cannot be read (text is not visible)

**Comment by URK96** [comment]
Thanks to report issue.

Windows 11 is beta release now. So Windows 11 can cause app crash issues.

I check application on Windows 11 (build 22000.120) and it works.

Can you give me your Windows 11 build version and System Language (or System Locale)?

**Comment by MenBS** [comment]
Chek on Win11 Build 22468.rs_prerelease/210921-1215
System Language is RU [(Russia
![211002_Untitled](https://user-images.githubusercontent.com/88586208/135714098-fdab4b1f-baef-442f-9a31-e9aa1752e589.png)
)]

**Comment by URK96** [comment]
Fix this issue and test on Win11 Build 22468.rs_prerelease with RU locale.

If other issue appear, create another issue on github
