### ISSUE TITLE
Buttons do not display correctly on smaller device

### ISSUE THREAD

**Issue by Shourn** [URK96/ResinTimer#16]
I have a smaller device (4.6" display, Android) and a lot of the buttons do not display correct.
Please see the attached screenshot.

![Screenshot_2021-08-14-09-03-45](https://user-images.githubusercontent.com/2538811/129438315-b290f60d-86f4-4fc1-91e5-18ad79460a48.jpg)

**Comment by URK96** [comment]
Thanks to report UI issue. I will fix on next update

**Comment by URK96** [comment]
Fixed version is already released. Have any layout issue now?
