### ISSUE TITLE
Gardening tab issue

### ISSUE THREAD

**Issue by kainili** [URK96/ResinTimer#17]
Any gardening timer set is deleted when changing tab or leaving the app.

Android 10
Latest Resin Timer app update

**Comment by kainili** [comment]
Also, I just noticed that all my furnishing building list was gone. And only 1 timer is saved, the others added get deleted after changing tab or leaving the app.

Otherwise I wanted to say thank you for this awesome app !

**Comment by URK96** [comment]
Thanks to report bug issue. I will fix that on next update

**Comment by kainili** [comment]
Both problems have been fixed with today's update ! 
Thank you so much for this awesome app !
