### ISSUE TITLE
What permissions or settings does the app need to receive notifications reliably?

### ISSUE THREAD

**Issue by dspjm** [URK96/ResinTimer#21]
It seems that sometimes the notification of resins are not delivered, do I need to set any permissions or settings to receive notification reliably?

**Comment by URK96** [comment]
Thanks to report issue. 
Notification is delivered on test. So i need to know your environment to solve this.
Can you comment your OS environment (Android, iOS, Windows)?

**Comment by URK96** [comment]
Ok, i see. I think that notification issue is appeared by Android policy.
I will check that part of code. If possible, i will fix it.

**Comment by dspjm** [comment]
> Ok, i see. I think that notification issue is appeared by Android policy.
> I will check that part of code. If possible, i will fix it.
> 
> Also if possible, try to disable and enable notification setting in application.

Thanks, it's probably not a bug. Maybe just killed or inhibited by android in the background.

**Comment by URK96** [comment]
Close this issue.

If other issue appear, create another issue on this repo.
