### ISSUE TITLE
Expedition sync?

### ISSUE THREAD

**Issue by machasins** [URK96/ResinTimer#25]
Is there any plans to add syncing for expeditions? I noticed on the "Real-Time Notes" page of the HoYoLAB app that they list all the expeditions currently being run and how much longer they have left. Are there any plans to incorporate this into the app, similar to the Resin sync it currently has? It'd be nice to have the option instead of the manual refresh currently.

Love the app, use it everyday! 

Thanks.

**Comment by URK96** [comment]
Thanks to suggestion :)

Expedition Sync feature is planned already, and it will add on future update x~x

**Comment by aymro** [comment]
The timer has been stopping at the status "complete" since I have assigned the new face Yelan on duty.
Database update is required, methinks.

**Comment by URK96** [comment]
Sorry for late reply....

Thanks to feedback app issue. I will update database and that issue until this weekend   x~x

**Comment by URK96** [comment]
Add expedition sync feature & DB update process is finished. Close this issue.
