### ISSUE TITLE
ResinTimer widget bug

### ISSUE THREAD

**Issue by Kdzh1** [URK96/ResinTimer#26]
![Screenshot_20220124-000211_One UI Home](https://user-images.githubusercontent.com/85634053/150697862-89abf37d-a00d-4c1f-9aed-6ea5f147778b.jpg)

This issue appeared after OneUI 4.0 update on Android. I can't see the resin and can't update the widget.

**Comment by URK96** [comment]
Thanks to report bug. I recognize that issue so i try to fix this issue.

I will upload update as soon as possible.

**Comment by URK96** [comment]
Fixed on 1.15.3
