### ISSUE TITLE
Resin reminders constantly resetting

### ISSUE THREAD

**Issue by machasins** [URK96/ResinTimer#27]
I use reminders for 120 resin and 150 resin, but they keep getting deleted. All that's left is the 160 resin alarm. I've replaced them a few times now, but they keep disappearing. 

Notifications for the garden being ready also did not appear recently. Unsure if this is related or even ongoing as the time between notifications is pretty long.

Also, setting a reminder for something like furniture or materials and then deleting that reminder still sends the notification. Not sure if this has been fixed since the last update since it takes a while to test (like 12 hours).

Thanks.

**Comment by URK96** [comment]
Thanks to report issue. I think changing DependencyService implements is problem. I fix as soon as possible

**Comment by URK96** [comment]
Fix on 1.15.3 update. If this issue appear again, reopen this issue.
