### ISSUE TITLE
Resin and Realm Currency Notifications not triggering

### ISSUE THREAD

**Issue by machasins** [URK96/ResinTimer#29]
For a couple of days now, none of my resin notifications are being triggered and my realm currency is stuck at 100% despite being collected multiple times.

I suspect that the sync function isn't working properly, because a few days ago I got a notification for 160 resin despite only being at around 40. I have not received resin notifications since that, but my resin count is tracked successfully.

 Also, when I collected my realm currency, the tracker shortly showed 0% but then suddenly jumped back to 100%. Since I enabled the realm currency sync, I have never been at 100%, yet it constantly shows at that (and the 'time to full' is just the current time, roughly).

Thanks.

**Comment by URK96** [comment]
Thanks for reporting issue.

Can you tell me what is your smartphone OS and app version?

**Comment by machasins** [comment]
I'm using a Samsung Galaxy S8, Android 9, and the app is version 1.16.1

Thanks.

**Comment by URK96** [comment]
Fix on v1.16.2 update
