### ISSUE TITLE
New <10 <20 Buttons remove all Resin

### ISSUE THREAD

**Issue by Serfrost** [URK96/ResinTimer#3]
I'm not sure what the intended function of these buttons are supposed to be but using either one simply sets Resin to 0 regardless of the current amount.

**Comment by URK96** [comment]
< 20, < 10 Button performs the remaining operations.
For example, when your resin remain 134, < 20 button make your resin to 14. In same case, < 10 button make your resin to 4.
If you have problem with new buttons, please use other exist buttons. Also, I will check this issue.
