### ISSUE TITLE
[Suggestion] "BACK" button/gesture to return on start screen

### ISSUE THREAD

**Issue by kainili** [URK96/ResinTimer#30]
Thank you for the hard work on your app ! 
I wanted to ask if it's possible to get on the start screen with back gesture or button instead of leaving completely the app (and double tap button/gesture to leave if not on start screen) ? I always leave the app accidentally and I thought it would be more optimized that way than having to load the app every time (I don't know if I'm the only one getting it closing when trying to get back on main start screen).

But it is just a suggestion, thank you for reading me !

**Comment by URK96** [comment]
Thanks to suggest idea!

I will add feature on v1.17.0 update

**Comment by kainili** [comment]
Thank you so much !

**Comment by kainili** [comment]
Guess I shouldn't have had closed it.

Please, if you may still consider doing it.
Thank you!

**Comment by URK96** [comment]
Sorry for late reply....

I already check that back feature is not apply yet, so i will add this feature next version again.

**Comment by kainili** [comment]
Back feature works great, thank you !
