### ISSUE TITLE
Can't load my wish log

### ISSUE THREAD

**Issue by Velvore** [URK96/ResinTimer#31]
![Screenshot_2022-03-26-20-25-30-949_com urk resintimer](https://user-images.githubusercontent.com/60406057/160241558-7abd5928-2f36-4f68-b968-2529b86807a3.jpg)

**Comment by URK96** [comment]
Did you input HoYoLAB Feedback URL?

Recently, we can't access wish log with HoYoLAB Feedback URL.
So, you can earn wish log URL in Genshin Impact log file.

Refer [this help document](https://www.notion.so/How-to-get-AuthKey-URL-5858d5f693dd4d6e8590a05d20b56cc0) to earn wish log URL.
