### ISSUE TITLE
Read resin count from hoyo API

### ISSUE THREAD

**Issue by YozenPL** [URK96/ResinTimer#33]
Is it possible for you to add the function to read the resin directly from hoyo API? There is a python project which is already doing this kind of stuff. 
https://github.com/thesadru/genshinstats

**Comment by URK96** [comment]
Thanks to suggest feature.

Sync resin feature is already added in Resin Timer application.
You can use that after enable 'Account Sync' setting in app setting

**Comment by YozenPL** [comment]
I did not saw it. Thanks for pointing it!
