### ISSUE TITLE
[ Suggestion ] Auto claim daily check-in reward

### ISSUE THREAD

**Issue by helmiau** [URK96/ResinTimer#34]
i give suggestion to make an option "Auto claim" on "Daily reward" feature.
like this repository https://github.com/darkGrimoire/hoyolab-daily-bot 
thank you

**Comment by URK96** [comment]
Thanks to suggest feature   x~x

Auto claim feature of Daily reward already plan to add on after version :)

**Comment by URK96** [comment]
Auto claim feature is added on Android version (v1.19.0)

Other platform will be added v1.19.x version later.

**Comment by Lii-Kun** [comment]
Will Auto claim be added for Honkai Star rail?

**Comment by URK96** [comment]
@Lii-Kun Honkai Star Rail Auto Claim feature will be updated :)

**Comment by URK96** [comment]
@Lii-Kun Honkai Star Rail Auto Claim feature is added on v1.21.0 release
