### ISSUE TITLE
Expedition Timer Not Resetting

### ISSUE THREAD

**Issue by LizzieTheRose** [URK96/ResinTimer#36]
So my expedition timers have been stuck for like a week now. I'm not sure how to fix it since it's auto-syncing (even though it's not auto-syncing), so I can't delete them. How do I fix this?

**Comment by URK96** [comment]
Did you try expedtion timers in manual mode?

If timer item type is sync, you can see skyblue cloud icon left top. Sync type items cannot delete manually. If you want to delete them, disable expedition sync mode.

**Comment by LizzieTheRose** [comment]
> Did you try expedtion timers in manual mode?
> 
> If timer item type is sync, you can see skyblue cloud icon left top. Sync type items cannot delete manually. If you want to delete them, disable expedition sync mode.

I can't figure out how to put it in manual mode without taking everything else off auto sync as well. ;;

**Comment by LizzieTheRose** [comment]
Nvm, I found it!
