### ISSUE TITLE
1.6업데이트 오류 관련 

### ISSUE THREAD

**Issue by leeseokjun96** [URK96/ResinTimer#4]
![Screenshot_20210204-031457_Resin Timer](https://user-images.githubusercontent.com/78501523/106791486-501be680-6698-11eb-9c66-9c171a6c61da.png)
특성책 알리미 ui 잘 안보입니다.

**Comment by URK96** [comment]
해당 문제 확인했습니다. 수정하여 업데이트 배포해드리겠습니다.

**Comment by URK96** [comment]
1.6.1 버전에서 수정되었습니다. 스토어에 업데이트가 표시되면 업데이트 진행 부탁드립니다 x~x
