### ISSUE TITLE
Genshin resin cap increase

### ISSUE THREAD

**Issue by Moravuscz** [URK96/ResinTimer#42]
Hi,
Today's update of Genshin brought with it an increase in Resin cap from 160 to 200.

Looks like you haven't worked on this in a while, but this should be an easy change.

Thanks

**Comment by JulGer** [comment]
+1

**Comment by URK96** [comment]
Thank you for your interest about this app.
 
I already finish to work about maximum resin, but i'm on business trip now so i cannot access my build and deploy system.

I will upload this update on weekend.

**Comment by URK96** [comment]
I finish to upload max resin increase update. (v1.24.0)
If have other issue on 1.24.0, create other issue or reopen this.

I intend to implement another major feature update once the migration of this app from Xamarin.Forms to .NET MAUI is complete.
Therefore, the Honkai Star Rail feature will be added after this migration work.
