### ISSUE TITLE
A typo in the 2x2 widget

### ISSUE THREAD

**Issue by Peacepot** [URK96/ResinTimer#5]
![20210223_233713](https://user-images.githubusercontent.com/79531964/108875776-1b180980-7630-11eb-92f3-5fe651a82a70.jpg)

Hello, just want to say that there's a typo in the 2x2 widget saying "Toady" instead of "Today", a minor issue but i hope it can be fixed, thx :)

**Comment by URK96** [comment]
Oh, this bug is my mistake. I will fix on next update. Thanks to report bug   x~x
