### ISSUE TITLE
Black Screen 

### ISSUE THREAD

**Issue by MoriRo** [URK96/ResinTimer#8]
Hello. With the 1.8.0 update, I only see a black screen if I Open the App. 

I use an iPhone SE 2 with the 14.5 iOS beta

**Comment by URK96** [comment]
Thanks to report black screen issue. I recommend to use non-beta version of iOS because of unstable. 
Also, I will test on that environment with simulator. If I find issue, I will fix it.

**Comment by URK96** [comment]
I found manifest error on iOS configuration. I fix it now and upload 1.8.1 update soon   x~x
