### ISSUE TITLE
apk file on v1.8.2

### ISSUE THREAD

**Issue by tingao** [URK96/ResinTimer#9]
Hi! Thanks for all the releases, can't find the apk file, tried to compile myself but can't figure out how to do it on android studio. Any chance you've the build ready?

**Comment by URK96** [comment]
Missing apk file is my mistake. I will upload apk file soon.
Also, this project use Xamarin.Forms framework with C# so you can't compile on android studio. If you want to compile this project, use Visual Studio with Xamarin SDK.

**Comment by tingao** [comment]
thanks! done [https://drive.google.com/uc?export=download&id=1LeDfjupBfHOvoA7TrMOFENa9g8Xac9xp](url)

**Comment by selurvedu** [comment]
@URK96 Hello! Could you please do the same for newer releases?

I was very happy to find your app and I really like that it does exactly what I was looking for. I use it daily and it really boosted my game progress. 👍

**Comment by URK96** [comment]
Sorry for late comment

I will upload newer release :)

**Comment by selurvedu** [comment]
Thank you!
